name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port 32574 -uroot -ppassword -e "SHOW DATABASES"
    - name: MySQL server from host
      run: |
        sudo yum install mysql-server
    - name: MySQL connection restart
      run: |
        sudo service mysqld restart
    - name: Setup Runner Database
      run: |
        MYSQL_PWD=password mysql -u root -e 'CREATE DATABASE IF NOT EXISTS bookDb;'
    - name: Junit Assignment Action
      id: assignmentAction
      uses: iam-abhi/junit-github-action@v0.9